### PR TITLE
Register callback in Clockwork::Test.manager

### PR DESCRIPTION
**Pull request by rahul342**
Same as https://github.com/kevin-j-m/clockwork-test/pull/33 (Had messed up commits while squashing in there)

### CODE REVIEW

**Comment by rahul342** [comment]
@kevin-j-m what would be a way to release a new version? We have been pulling from master, but would love to remove that from our Gemfile.

**Comment by rahul342** [comment]
cc @cxmcc

**Comment by kevin-j-m** [comment]
Hi @rahul342, thanks for letting me know you're depending on this. I will __try__ to get a release out this week. I hope you can appreciate that my time has been a bit pre-occupied/used differently lately, as I'm sure yours has as well.

**Comment by kevin-j-m** [comment]
I've released version 0.4.0, which includes this change. Thank you again for your contribution.

**Comment by rahul342** [comment]
Thank you!

**Pull request merged**
